name: Clear Workflow Runs

on:
  schedule:
    - cron: '0 23 * * *' # 每周量子定时运行一次
  workflow_dispatch:     # 支持手动触发

jobs:
  del_runs:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: read
    steps:
      - name: Clean Up Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0          # 不保留过往历史天数
          keep_minimum_runs: 1   # 仅保留最近的 1 次运行记录
