#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: Build 25.12 MosDNS

on:
  schedule:
    - cron: "12 22 * * *"  # 北京时间早上 6 点12
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Fetch latest release tag from mosdns
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          
      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest mosdns files
        run: |
          
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | grep -oP '"browser_download_url":\s*".*aarch64_generic-openwrt-25.12.tar.gz"' | cut -d '"' -f 4)
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | grep -oP '"browser_download_url":\s*".*aarch64_cortex-a53-openwrt-25.12.tar.gz"' | cut -d '"' -f 4)
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | grep -oP '"browser_download_url":\s*".*x86_64-openwrt-25.12.tar.gz"' | cut -d '"' -f 4)
          
          tar --one-top-level=aarch64_generic-openwrt-25.12 -xvzf aarch64_generic-openwrt-25.12.tar.gz
          tar --one-top-level=aarch64_cortex-a53-openwrt-25.12 -xvzf aarch64_cortex-a53-openwrt-25.12.tar.gz
          tar --one-top-level=x86_64-openwrt-25.12 -xvzf x86_64-openwrt-25.12.tar.gz
      - name: Organize files for aarch64_cortex-a53&x86_64
        run: |
          mkdir mosdns_x86_64 mosdns_aarch64_cortex-a53 mosdns_aarch64_generic
          cp x86_64-openwrt-25.12/packages_ci/*.apk mosdns_x86_64/
          cp aarch64_cortex-a53-openwrt-25.12/packages_ci/*.apk mosdns_aarch64_cortex-a53/
          cp aarch64_generic-openwrt-25.12/packages_ci/*.apk mosdns_aarch64_generic
          
      - name: Create install.sh scripts
        run: |
          cat <<EOF > mosdns_x86_64/install.sh
          #!/bin/sh
          apk update
          if [ $? -ne 0 ]; then
              echo "update failed"
              exit 1
          fi
          apk add --allow-untrusted *.apk
          EOF
          chmod +x mosdns_x86_64/install.sh
          cp mosdns_x86_64/install.sh mosdns_aarch64_cortex-a53/install.sh
          cp mosdns_x86_64/install.sh mosdns_aarch64_generic/install.sh

      - name: Move mosdns directories to makeself
        run: |
          mv mosdns_x86_64 makeself/
          mv mosdns_aarch64_cortex-a53 makeself/
          mv mosdns_aarch64_generic makeself/ 
      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh mosdns_x86_64/ 25-mosdns_${{ env.LATEST_TAG }}_x86_64.run "by github action" ./install.sh
          ./makeself.sh mosdns_aarch64_cortex-a53/ 25-mosdns_${{ env.LATEST_TAG }}_aarch64_cortex-a53.run "by github action" ./install.sh
          ./makeself.sh mosdns_aarch64_generic/ 25-mosdns_${{ env.LATEST_TAG }}_aarch64_generic.run "by github action" ./install.sh
          
      - name: Check file sizes
        run: |
          ls -lh makeself/*.run
   
      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
